# Generated by Django 2.1.1 on 2018-09-30 16:59

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
from django.contrib.postgres.operations import HStoreExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        HStoreExtension(),
        migrations.CreateModel(
            name='AuctionItem',
            fields=[
                ('auctionId', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('startBidingDate', models.DateField(help_text='format yyyy-MM-dd', null=True)),
                ('endBidingDate', models.DateField(help_text='format yyyy-MM-dd')),
                ('lat', models.FloatField(null=True)),
                ('long', models.FloatField(null=True)),
                ('data', django.contrib.postgres.fields.hstore.HStoreField()),
            ],
        ),
    ]
