# Generated by Django 2.1.1 on 2018-09-30 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='startBidingDate',
            field=models.DateField(help_text='format yyyy-MM-dd'),
        ),
    ]
